### ISSUE TITLE
Error when querying prices from Oracle

### ISSUE THREAD

**Issue by unl1k3ly** [terra-money/terra-sdk-python#12]
### Description

Can't get prices from oracle using `terra.oracle.exchange_rate('uusd')`. 

### What I Did

```
>>> terra.oracle.exchange_rates()
Coins('13.363899366807197127uaud,12.507059505101729225ucad,9.299427851702487944uchf,66.68376033969933393ucny,8.482260343541582751ueur,7.298704192986536663ugbp,80.525231868325979739uhkd,756.729796676163555129uinr,1126.838181910159832044ujpy,12907.245538546065628807ukrw,29579.640321016654708655umnt,7.182148051564867481usdr,85.923147806798035292usek,13.799548482083606946usgd,325.581339483602357661uthb,10.371857135833388667uusd')
>>> terra.oracle.exchange_rate('uusd')
Traceback (most recent call last):
  File "/snap/pycharm-community/238/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/v-terra/PycharmProjects/x/venv/lib/python3.8/site-packages/terra_sdk/client/lcd/api/_base.py", line 29, in decorator
    return instance._run_sync(async_call(instance, *args, **kwargs))
  File "/home/v-terra/PycharmProjects/x/venv/lib/python3.8/site-packages/terra_sdk/client/lcd/api/_base.py", line 13, in _run_sync
    return self._c.loop.run_until_complete(coroutine)
  File "/home/v-terra/PycharmProjects/x/venv/lib/python3.8/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/home/v-terra/PycharmProjects/x/venv/lib/python3.8/site-packages/terra_sdk/client/lcd/api/oracle.py", line 93, in exchange_rate
    rates = await self.exchange_rates()
TypeError: object Coins can't be used in 'await' expression
```

**Comment by hanjukim** [comment]
@brycepratt Could you handle this issue?

**Comment by brycepratt** [comment]
Noticed this bug during bombay migration - it's fixed on the bombay branch but I've now included an immediate fix in the above PR.
