### ISSUE TITLE
I can't do a simple swap. Gas_adjustment asks me for coin format

### ISSUE THREAD

**Issue by RamiroRama** [terra-money/terra-sdk-python#31]
- Terra_sdk version: terra-sdk-1.0.0b1
- Python version: 3.8
- Operating System: Ubuntu 20.04

### Description

I'm trying to do a swap, with the following code, it worked perfectly in col-4. Since the upgrade, I can't get it to work. Right now it is giving me the format error in gas_adjustment. It was never a coin format and I think it shouldn't ask for it in that format, I assume it as a bug

### What I Did

```
tx = wallet.create_and_sign_tx(
            msgs=[swap],
            gas_prices= str(gas_prices_live["uusd"]),
            gas_adjustment="1.4"
            )
```

### Error i get

Traceback (most recent call last):
  File "/home/rama/eclipse-workspace/Probar_Com_Terra/PruebaGral.py", line 160, in <module>
    tx = wallet.create_and_sign_tx(
  File "/home/rama/.local/lib/python3.8/site-packages/terra_sdk/client/lcd/wallet.py", line 136, in create_and_sign_tx
    self.create_tx(
  File "/home/rama/.local/lib/python3.8/site-packages/terra_sdk/client/lcd/wallet.py", line 93, in create_tx
    return self.lcd.tx.create(
  File "/home/rama/.local/lib/python3.8/site-packages/terra_sdk/client/lcd/api/_base.py", line 29, in decorator
    return instance._run_sync(async_call(instance, *args, **kwargs))
  File "/home/rama/.local/lib/python3.8/site-packages/terra_sdk/client/lcd/api/_base.py", line 13, in _run_sync
    return self._c.loop.run_until_complete(coroutine)
  File "/home/rama/.local/lib/python3.8/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/home/rama/.local/lib/python3.8/site-packages/terra_sdk/client/lcd/api/tx.py", line 64, in create
    self.estimate_fee(
  File "/home/rama/.local/lib/python3.8/site-packages/terra_sdk/client/lcd/api/_base.py", line 29, in decorator
    return instance._run_sync(async_call(instance, *args, **kwargs))
  File "/home/rama/.local/lib/python3.8/site-packages/terra_sdk/client/lcd/api/_base.py", line 13, in _run_sync
    return self._c.loop.run_until_complete(coroutine)
  File "/home/rama/.local/lib/python3.8/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/home/rama/.local/lib/python3.8/site-packages/terra_sdk/client/lcd/api/tx.py", line 106, in estimate_fee
    gas_prices_coins = Coins(gas_prices)
  File "/home/rama/.local/lib/python3.8/site-packages/terra_sdk/core/coins.py", line 70, in __init__
    self._coins = Coins.from_str(arg)._coins
  File "/home/rama/.local/lib/python3.8/site-packages/terra_sdk/core/coins.py", line 50, in from_str
    return Coins(Coin.from_str(cs) for cs in coin_strings)
  File "/home/rama/.local/lib/python3.8/site-packages/terra_sdk/core/coins.py", line 80, in __init__
    for coin in coins:
  File "/home/rama/.local/lib/python3.8/site-packages/terra_sdk/core/coins.py", line 50, in <genexpr>
    return Coins(Coin.from_str(cs) for cs in coin_strings)
  File "/home/rama/.local/lib/python3.8/site-packages/terra_sdk/core/coin.py", line 94, in from_str
    raise ValueError(f"failed to parse Coin: {string}")
ValueError: failed to parse Coin: 1.4

**Comment by Vritra4** [comment]
fixed with 1.0.0b3 :)
